import type { Metadata } from 'next'
import { LegalPage } from '@/components/ui/LegalPage'
import { affiliate, siteConfig } from '@/lib/site'

export const metadata: Metadata = {
  title: 'Privacy Policy',
  alternates: { canonical: '/privacy' },
}

export default function PrivacyPage() {
  return (
    <LegalPage title="Privacy Policy" updated="September 2026">
      <p>
        Covison (&ldquo;we&rdquo;, &ldquo;our&rdquo;, &ldquo;us&rdquo;) is committed to protecting
        your personal information and being transparent about how we collect, use, and safeguard
        it. This policy applies to covison.co, crm.covison.com, and any other services we operate,
        and explains what data we collect, why we collect it, how long we keep it, and the rights
        you have over it.
      </p>

      <h2>1. Who we are</h2>
      <p>
        Covison is affiliated with {affiliate.name}, a company registered in {affiliate.country}{' '}
        under company number {affiliate.companyNumber}, with a registered address at{' '}
        {affiliate.address}. For the purposes of data protection law, {affiliate.name} is the data
        controller for personal information processed through our website and products.
      </p>

      <h2>2. Information we collect</h2>
      <p>Information you give us directly:</p>
      <ul className="flex list-disc flex-col gap-2 pl-5">
        <li>
          Contact details such as your name, email address, phone number, and company, when you
          book a call, message us on WhatsApp, fill in a contact form, or email us.
        </li>
        <li>Project details you share with us while scoping or delivering an engagement.</li>
        <li>
          Account information if you sign up for Covison CRM, such as your name, email, workspace
          details, and any data you choose to store within the product (contacts, deals, tasks,
          and similar records you create).
        </li>
        <li>Any other information you choose to send us, for example in an email or message.</li>
      </ul>
      <p>Information collected automatically:</p>
      <ul className="flex list-disc flex-col gap-2 pl-5">
        <li>
          Basic analytics data, such as pages visited, time on page, referral source, device type,
          and approximate location derived from IP address, used to understand how our site is
          used and to improve it.
        </li>
        <li>
          Standard technical logs (IP address, browser type, timestamps) generated by our hosting
          and security infrastructure.
        </li>
      </ul>

      <h2>3. Cookies and similar technologies</h2>
      <p>
        We use a limited set of cookies and similar technologies: essential cookies needed for the
        site and Covison CRM to function correctly (such as remembering your theme preference or
        keeping you signed in), and analytics cookies that help us understand aggregate usage. You
        can control or disable non-essential cookies through your browser settings; blocking
        essential cookies may affect how the site or product functions.
      </p>

      <h2>4. How we use your information</h2>
      <p>We use the information we collect to:</p>
      <ul className="flex list-disc flex-col gap-2 pl-5">
        <li>Respond to your inquiries and provide the services or product you have requested.</li>
        <li>Operate, maintain, and improve Covison CRM and our website.</li>
        <li>
          Send you service-related communications, and, only with your consent, updates about our
          services.
        </li>
        <li>Understand how our site and product are used, in aggregate, to guide improvements.</li>
        <li>Meet our legal, tax, and regulatory obligations.</li>
      </ul>
      <p>
        We do not sell your personal information to third parties, and we do not use your data to
        train third-party AI models beyond what is necessary to operate features you have
        knowingly opted into.
      </p>

      <h2>5. Legal basis for processing</h2>
      <p>
        Where UK data protection law applies, we rely on one or more of the following legal bases:
        your consent (for example, for marketing communications), performance of a contract (for
        example, delivering a project or operating your Covison CRM account), our legitimate
        interests (for example, keeping our services secure and improving them), and compliance
        with a legal obligation.
      </p>

      <h2>6. How we share your information</h2>
      <p>
        We share personal information only where necessary: with service providers who help us
        operate our website, hosting, communications, scheduling, and analytics (bound by
        confidentiality and data protection obligations); when required by law, regulation, or a
        valid legal process; or with your consent. We do not sell or rent your personal
        information.
      </p>

      <h2>7. International data transfers</h2>
      <p>
        Some of the service providers we use to operate our website and products may process data
        outside the United Kingdom. Where this happens, we take steps to ensure an appropriate
        level of protection is maintained, consistent with UK data protection law.
      </p>

      <h2>8. Data retention</h2>
      <p>
        We retain personal information for as long as necessary to provide our services, maintain
        your Covison CRM account, comply with our legal and accounting obligations, and resolve
        disputes. When information is no longer needed for these purposes, we delete or anonymize
        it.
      </p>

      <h2>9. Your rights</h2>
      <p>
        Depending on your location, you may have the right to access the personal information we
        hold about you, correct inaccurate information, request deletion, restrict or object to
        processing, request a copy of your data in a portable format, and withdraw consent at any
        time where processing is based on consent. To exercise any of these rights, contact us
        using the details below. If you are in the UK and remain unsatisfied with our response,
        you have the right to lodge a complaint with the Information Commissioner&apos;s Office
        (ICO) at ico.org.uk.
      </p>

      <h2>10. Children&apos;s privacy</h2>
      <p>
        Our services are directed at businesses and are not intended for individuals under 16. We
        do not knowingly collect personal information from children.
      </p>

      <h2>11. Security</h2>
      <p>
        We take reasonable technical and organizational measures to protect the information we
        hold against unauthorized access, loss, misuse, or alteration. No method of transmission
        or storage is completely secure, so we cannot guarantee absolute security.
      </p>

      <h2>12. Changes to this policy</h2>
      <p>
        We may update this policy from time to time to reflect changes to our practices or for
        legal or regulatory reasons. The &ldquo;Last updated&rdquo; date at the top of this page
        reflects when it was last revised.
      </p>

      <h2>13. Contact us</h2>
      <p>
        For any privacy questions or to exercise your rights, email us at{' '}
        <a href={`mailto:${siteConfig.email}`}>{siteConfig.email}</a> or message us on WhatsApp.
      </p>
    </LegalPage>
  )
}
